### ISSUE TITLE
Latest build looks good but is still not accurate

### ISSUE THREAD

**Issue by STashakkori** [LaBatata101/grep_bin#5] opened 2021-11-15 00:41 UTC
It looks like a great combo of the new and older versions but it still seems to skip occurrences. Have tested with 00, 01, 0F, 2E2E and noticed several occurrences in the output that don't get highlighted. I will take a look to see whats happening

**Comment by STashakkori** [comment] 2021-11-15 01:18
Yea this is weird. I created a file and in it I wrote only the following two characters: E0. And then if I run:
./grep_bin file 00
I get the following output that makes no sense:
test2.txt
00000000:  45 30 0A 00 00 00 00 00  00 00 00 00 00 00 00 00   |E0..............|
00000000:  45 30 0A 00 00 00 00 00  00 00 00 00 00 00 00 00   |E0..............|
00000000:  45 30 0A 00 00 00 00 00  00 00 00 00 00 00 00 00   |E0..............|
00000000:  45 30 0A 00 00 00 00 00  00 00 00 00 00 00 00 00   |E0..............|
00000000:  45 30 0A 00 00 00 00 00  00 00 00 00 00 00 00 00   |E0..............|
00000000:  45 30 0A 00 00 00 00 00  00 00 00 00 00 00 00 00   |E0..............|
00000000:  45 30 0A 00 00 00 00 00  00 00 00 00 00 00 00 00   |E0..............|
00000000:  45 30 0A 00 00 00 00 00  00 00 00 00 00 00 00 00   |E0..............|
00000000:  45 30 0A 00 00 00 00 00  00 00 00 00 00 00 00 00   |E0..............|
00000000:  45 30 0A 00 00 00 00 00  00 00 00 00 00 00 00 00   |E0..............|
00000000:  45 30 0A 00 00 00 00 00  00 00 00 00 00 00 00 00   |E0..............|
00000000:  45 30 0A 00 00 00 00 00  00 00 00 00 00 00 00 00   |E0..............|
00000000:  45 30 0A 00 00 00 00 00  00 00 00 00 00 00 00 00   |E0..............|
00000010:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
00000010:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
00000010:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
00000010:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
00000010:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
00000010:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
00000010:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
00000010:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
00000010:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|

I don't think this is working the way it's supposed to. If you notice on the ascii dump on the right, it seems to duplicate characters over and over. So perhaps the bug is not that its missing occurrences, its that its multiplying characters in the printed output and only highlighting the original character and not highlighting the duplicates. Instead of printing E0 once it prints it 13 times. I can only assume it is doing this with every character it finds. The addresses in green on the left get multiplied as well.

**Comment by LaBatata101** [comment] 2021-11-15 22:20
Interesting edge case you found, these 00 bytes shouldn't even be showing because the file you created doesn't contain 00 bytes.

`grep_bin` reads the file in 8KiB(8192 bytes) chunks, which is the buffer, so when a large file is read it doesn't put all the file contents in the memory as the file in your example has only 3 bytes leaving us with 8189 empty bytes in the buffer that are 0 by default so that is where these 00 bytes are coming from and I don't know exactly how to solve this issue.

As for the coloring problem I have an idea of what may the cause, I'll look into that later.

**Comment by LaBatata101** [comment] 2021-11-26 22:00
Fixed in lastest [release](https://github.com/LaBatata101/grep_bin/releases/tag/v1.1.1).
Thanks for helping me find bugs in the code!

**Closed as completed by LaBatata101** 2021-11-26 22:00 UTC
Labels: bug
